"""knowledge_tables

Revision ID: 41182cff3e23
Revises: 4b2c9a06ff5c
Create Date: 2026-04-28 10:15:35.099022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41182cff3e23'
down_revision: Union[str, None] = '4b2c9a06ff5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_slug', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('visible_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visible_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed categories
    import json
    cats = [
        ("massage", "Массаж", "💆", "Техники, анатомия, протоколы", None, 1, None),
        ("massage-anatomy", "Анатомия", "🦴", None, "massage", 1, None),
        ("massage-trigger", "Триггерные точки", "🎯", None, "massage", 2, None),
        ("massage-techniques", "Техники массажа", "🤲", None, "massage", 3, None),
        ("massage-videos", "Видеотека", "🎬", None, "massage", 4, None),
        ("massage-contra", "Противопоказания", "⚠️", None, "massage", 5, None),
        ("service", "Сервис", "💼", "Продажи, клиентский опыт, стандарты", None, 2, None),
        ("service-sales", "Продажи", "💰", None, "service", 1, None),
        ("service-cx", "Клиентский опыт", "⭐", None, "service", 2, None),
        ("service-objections", "Работа с возражениями", "🗣", None, "service", 3, None),
        ("service-scripts", "Скрипты", "📋", None, "service", 4, None),
        ("service-appearance", "Стандарты внешнего вида", "👔", None, "service", 5, None),
        ("admin-docs", "Для администраторов", "🗂", "Справочники и стандарты", None, 3,
         json.dumps(["manager", "owner", "superadmin", "teacher", "senior_master"])),
        ("admin-services", "Справочник услуг", "📖", None, "admin-docs", 1,
         json.dumps(["manager", "owner", "superadmin", "teacher", "senior_master"])),
        ("admin-booking", "Работа с записями", "📅", None, "admin-docs", 2,
         json.dumps(["manager", "owner", "superadmin", "teacher", "senior_master"])),
        ("admin-reception", "Стандарты приёма клиентов", "🤝", None, "admin-docs", 3,
         json.dumps(["manager", "owner", "superadmin", "teacher", "senior_master"])),
        ("admin-faq", "Частые вопросы клиентов", "❓", None, "admin-docs", 4,
         json.dumps(["manager", "owner", "superadmin", "teacher", "senior_master"])),
    ]
    op.execute(
        "INSERT INTO knowledge_categories (slug, title, icon, description, parent_slug, order_index, visible_roles) VALUES "
        + ", ".join(
            f"('{c[0]}', '{c[1]}', '{c[2]}', {repr(c[3]) if c[3] else 'NULL'}, "
            f"{repr(c[4]) if c[4] else 'NULL'}, {c[5]}, "
            f"{repr(c[6]) if c[6] else 'NULL'})"
            for c in cats
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_articles')
    op.drop_table('knowledge_categories')
    # ### end Alembic commands ###
