"""documents_table

Revision ID: 85b8523c632c
Revises: 41182cff3e23
Create Date: 2026-04-28 11:17:34.946024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85b8523c632c'
down_revision: Union[str, None] = '41182cff3e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('visible_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed documents
    import json
    S3 = "https://storage.yandexcloud.net/rehabyou-storage/documents"
    docs = [
        ("Мастер 2.0 — Программа развития", f"{S3}/Мастер_2_0.html", "master",
         json.dumps(["master","senior_master","teacher","novice"]), 1),
        ("Стандарт мастера 2026", f"{S3}/Стандарт_мастера_2026.html", "master",
         json.dumps(["master","senior_master","teacher","novice"]), 2),
        ("Администратор 2.0 — Программа развития", f"{S3}/Администратор_2_0.html", "admin",
         json.dumps(["manager","owner","superadmin","senior_master","teacher"]), 1),
        ("Стандарт администратора 2026", f"{S3}/Стандарт_администратора_2026.html", "admin",
         json.dumps(["manager","owner","superadmin","senior_master","teacher"]), 2),
        ("Бренд-стратегия 2026", f"{S3}/Бренд-стратегия_2026.html", "brand", None, 1),
    ]
    for title, url, cat, roles, idx in docs:
        op.execute(
            f"INSERT INTO documents (title, url, category, visible_roles, order_index) "
            f"VALUES ('{title}', '{url}', '{cat}', {repr(roles) if roles else 'NULL'}, {idx})"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
